### ISSUE TITLE
Bring up to speed

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/react-formly#2]
This repo/library is pretty immature. angular-formly has left it in the dust with regards to the simplicity/extensibility of the API as well. @hossman333 has expressed interest in making this a real thing. Let's make that happen :-)

One of the main things I want to do with this is to look at the angular-formly API and see what makes sense in react-formly. Obviously stuff like `template`, `templateUrl`, `controller`, and `link` wont really make sense for us. But `apiCheck` and `defaultOptions` make a lot of sense. I want to make it so that if people decide to switch from angular to react or react to angular, they should be able to accomplish this without totally restructuring all of their field configurations (minor changes obviously will probably be necessary).

**Comment by jjstrat3** [comment]
Maybe start by breaking things out into a list?  It would be helpful for would-be contributors like myself if there was some plan of attack organized by priority that we could chip away at.  We already use angular-formly at my job, and with a new project that I'm leading being written mostly in React, I'd love to lend a hand in translating the features of angular-formly to react-formly on a case-by-case basis!

**Comment by kentcdodds** [comment]
Hi @jjstrat3! Thanks for your interest in contributing!

I currently don't actually have any use case for react-formly, but that may change as I'm changing jobs and will be start doing React. I'm not certain whether I'll need/use react-formly at that new job. If not, then it's unlikely I'll give react-formly much attention. However if I do, then this project will get a lot of love :-)

Why don't we go with this. Feel free to start using the library as it stands today and make changes as you need them (via Pull Requests). If I can see that you're serious about using this library and contributing to it, I'll give you commit access. That's how I took ownership of angular-formly and it worked out pretty well :D

**Comment by jjstrat3** [comment]
@kentcdodds Congrats on the new job!  I noticed via Twitter that you've been digging into React more lately.  If you're like me, you no doubt have a had more than a few "why doesn't Angular do it this way?!" moments. ;)

In terms of react-formly, that sounds great.  We don't currently have a feature in scope on my current project that would require react-formly, but I'd want to contribute to it as time allows just because I love angular-formly and think the react community would really benefit from having something similar.

**Comment by kentcdodds** [comment]
Sounds awesome :D And thanks!
