### ISSUE TITLE
Distribution build includes React

### ISSUE THREAD

**Issue by astrism** [formly-js/react-formly#4]
Webpack is packing all of React in the build, @kentcdodds I might spend a few minutes later today checking out how angular-formly gets around this.

**Comment by kentcdodds** [comment]
@astrism, are you doing React stuff? Awesome! You'll want to look at `externals`.

**Comment by astrism** [comment]
I am! Thanks, I'll check it out.

**Comment by kentcdodds** [comment]
react-formly is definitely a ways behind angular-formly and could use a little more standardization, but I think you'll still find it valuable and you can (of course) make updates to it as you are still an owner on this org :-)
