### ISSUE TITLE
Use JS instead of JSX for component

### ISSUE THREAD

**Issue by astrism** [formly-js/react-formly#7]
To allow library to be required without being compiled.

**Comment by kentcdodds** [comment]
People who don't want to transpile source should use the dist

**Comment by astrism** [comment]
I switched main in package.json to point to dist, but after I did that I've noticed some libraries just write in JS to avoid this issue and point to index.js or whatever top level file. Hence this issue, you think its cool to just leave it pointed to dist then?

**Comment by kentcdodds** [comment]
Yeah, let's leave it pointing to dist

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by astrism** [comment]
Will do
